// QView Stage-1 RETAINED host (WebGPU). spec/qview-protocol.md.
//
// Unlike the immediate-mode POC (runtime/web/app.js), this host keeps a RETAINED
// node tree (node_id -> record). The wasm builds it once via create/set_attr/on,
// then mutates it surgically from the on_event dispatcher. present() re-encodes
// the current tree. Node identity (and thus future focus/caret/scroll) is the
// node_id, preserved across frames — never a blind full re-emit.
import { KIND, ATTR, EVENT, EVENT_NAME, SURFACE, unpackColor, PROTOCOL_VERSION } from './protocol.js';

// Build stamp (date + sha), regenerated by the build step. Dynamically imported
// with a fallback so a fresh checkout without a build still loads (version.js is
// a gitignored artifact, always present in a built/deployed bundle).
let BUILD = 'dev';
try { ({ BUILD } = await import('./version.js')); } catch {}
import { initGPU, drawPrim, sdfTexture, beginFrame, endFrame, DPR } from './gpu.js';
import { drawPopup as drawMenu, hitPopup as hitMenu } from './popup.js';
import { widgetFor } from './widgets.js';
import { Scene } from './scene.js';
import { computeLayout } from './arrange.js';
import { resolvePlatform } from './platform.js';
import { themeFor } from './theme.js';

// One self-drawn renderer, three looks: iOS-ish on iOS, Material-ish on Android,
// a neutral house look on desktop. The platform is resolved once (sniff +
// ?platform= override); the per-platform theme tokens flow to every widget via
// r.platform / r.theme. Shaders and the protocol are unchanged — only tokens and
// (for structurally-different controls) per-platform draw variants differ.
// Mutable so the platform dropdown can RE-THEME the gallery live (pick Android ->
// Material). Starts from device detection / ?platform=; setPlatform() swaps it.
let PLATFORM = resolvePlatform();
let THEME = themeFor(PLATFORM);
// Catalog id of a platform option (1012..1015) -> theme platform key.
const OPTION_PLATFORM = { 1012: 'ios', 1013: 'android', 1014: 'desktop', 1015: 'desktop' };
function setPlatform(p) {
  if (!p || p === PLATFORM) return;
  PLATFORM = p; THEME = themeFor(p);
  renderCtx.theme = THEME; renderCtx.platform = PLATFORM;   // live-update the render context
  render();
}

const log = (m) => { const el = document.getElementById('log'); if (el) el.textContent = m; console.log('[qview]', m); };

// Host-owned glyph catalog (Stage-1 text-by-id; no strings cross wasm). A label
// whose text_id < CATALOG.length shows that string; otherwise the id is rendered
// as an integer (the POC's `number` path — live counters etc.).
const CATALOG_BASE = 1000;  // catalog ids are 1000+, so small ints render as numbers
const CATALOG = [
  'Widget gallery',  // 0
  'Label',           // 1
  'Button',          // 2
  'Checkbox',        // 3
  'Switch',          // 4
  'Radio A',         // 5
  'Radio B',         // 6
  'Slider',          // 7
  'Progress',        // 8
  'Dropdown',        // 9  (the row's name label)
  'Box',             // 10
  'Tap +1',          // 11
  'iOS',             // 12  dropdown options (selected value shows in the field)
  'Android',         // 13
  'Windows',         // 14
  'Linux',           // 15
  'Grouped',         // 16  group heading
  'In a group',      // 17  group sub-label
  'Long Click',      // 18  the context-menu touch area title
  'Cut',             // 19  context-menu items
  'Copy',            // 20
  'Paste',           // 21
];

// ---- the retained tree (generic, VALIDATED applier) --------------------------
// Scene owns the node tree + the five ops, schema-validating each before it
// touches the tree (spec §"Host obligations"). This host is one backend over it;
// the soft renderer is another. nodes/ROOT alias into the scene so the render +
// input code below reads unchanged.
const scene = new Scene({ onReject: (m) => log('drop: ' + m) });
const nodes = scene.nodes;
const ROOT = scene.ROOT;
// Evict glyph caches when the scene removes a node.
scene.onNodeRemoved = (id) => { glyphCache.delete(id); glyphKey.delete(id); };

let glyphCache = new Map();  // nodeId -> {tex,view,w,h}; rebuilt only when text changes
let glyphKey = new Map();    // nodeId -> last text string used, to skip rebuilds
let pressedId = null;
let instance;

function textStringFor(node) {
  const id = node.attrs.get(ATTR.text_id);
  if (id === undefined) return null;
  const n = Number(id);
  // text_id >= CATALOG_BASE is a catalog string; below it is a literal integer
  // (e.g. a live counter), so 'show the number 0' never collides with CATALOG[0].
  return (n >= CATALOG_BASE && n - CATALOG_BASE < CATALOG.length) ? CATALOG[n - CATALOG_BASE] : String(n);
}
function glyphFor(node) {
  const str = textStringFor(node);
  if (str === null) return null;
  if (glyphKey.get(node.id) !== str) {           // surgical: only a changed text re-rasterizes
    glyphCache.set(node.id, sdfTexture(str));
    glyphKey.set(node.id, str);
  }
  return glyphCache.get(node.id);
}

// ---- the wasm import face: the validated Scene ops + a backend present() -----
// Scene.face wires create/set_attr/remove/on to the validated applier; present()
// is this backend's frame commit (render + drain the mutation log). A set_attr
// may change a node's text, so we evict its glyph key around the applier.
function ops() {
  const sceneFace = scene.face(() => {
    render();
    const m = scene.drainMuts();
    if (m.length) log('mutate: ' + m.join(', '));
  });
  return {
    env: { out: () => {} },
    qview: {
      ...sceneFace,
      set_attr: (id, attr, value) => { glyphKey.delete(Number(id)); sceneFace.set_attr(id, attr, value); },
    },
  };
}

// ATTR.surface role tag -> theme token key (the translucent material fills).
const SURFACE_KEY = { [SURFACE.none]: 'none', [SURFACE.surface]: 'surface', [SURFACE.material]: 'material', [SURFACE.materialThin]: 'materialThin', [SURFACE.scrim]: 'scrim' };

// ---- render: walk the retained tree, dispatch each node to its widget --------
// `layoutMap` (id -> {x,y,w,h}) holds resolved geometry from the arrange pass
// (stacks own their children's coords). When a node has a layout entry, r.attr
// returns its laid-out x/y/w/h transparently — widgets read geometry the same
// way whether they're absolute or inside an HStack/VStack.
let layoutMap = new Map();
const GEOM = { [ATTR.x]: 'x', [ATTR.y]: 'y', [ATTR.w]: 'w', [ATTR.h]: 'h' };
// Host-managed vertical scroll: the canvas stays viewport-sized; the whole scene
// is translated up by scrollY at draw time (and touches translated down to match),
// so content taller than the screen is reachable without native scroll fighting
// the slider/long-press gestures. The pinned top bar opts out (drawn unshifted).
let scrollY = 0, contentH = 0, viewportH = 0;
const renderCtx = {
  pass: null, drawPrim, sdfText: sdfTexture, theme: THEME, platform: PLATFORM,
  attr: (node, a, dflt) => {
    const g = GEOM[a]; const lay = g && layoutMap.get(node.id);
    let v = lay ? lay[g] : node.attrs.get(a);
    v = v === undefined ? dflt : Number(v);
    if (a === ATTR.y && !node._pinned) v -= scrollY;     // translate scene up
    return v;
  },
  color: (node, a, dflt) => { const v = node.attrs.get(a); return v === undefined ? dflt : unpackColor(v); },
  // Resolve a node's fill, honoring a semantic ATTR.surface role (theme-resolved
  // translucent material) over a literal ATTR.fill over the given default.
  surfaceFill: (node, dflt) => {
    const role = node.attrs.get(ATTR.surface);
    if (role !== undefined) {
      const key = SURFACE_KEY[Number(role)];
      if (key && key !== 'none') return THEME[key] ?? dflt;
      if (key === 'none') return null;
    }
    const lit = node.attrs.get(ATTR.fill);
    return lit === undefined ? dflt : unpackColor(lit);
  },
  textFor: (node) => glyphFor(node),
  glyphForId: (textId) => glyphForCatalog(textId),
  isPressed: (id) => id === pressedId,
  isOpen: (id) => id === openDropdownId,
};

// The node currently showing a menu (one open at a time), or null. Any widget
// exposing menuSpec(node, r) can raise the shared popup; today that's the
// dropdown, tomorrow a context menu.
let openDropdownId = null;
// A context menu (long-press / right-click) raised at a point: its popup spec +
// the node it belongs to. Separate from openDropdownId (anchored differently).
let contextSpec = null, contextNode = null;

// The menu spec for the currently-open node (or null) — built fresh each use so
// it reflects current selection/geometry. The host injects the viewport (CSS px)
// so the popup can flip/clamp to stay on-screen.
function openMenuSpec() {
  if (openDropdownId === null) return null;
  const n = nodes.get(openDropdownId);
  const w = n && widgetFor(n.kind);
  if (!w || !w.menuSpec) return null;
  return withViewport(w.menuSpec(n, renderCtx));
}

// Inject the viewport (CSS px) into a popup spec so it can flip/clamp on-screen.
function withViewport(spec) {
  if (spec) {
    const cv = document.getElementById('gpu');
    if (cv) spec.viewport = { w: cv.clientWidth, h: cv.clientHeight };
  }
  return spec;
}

// A glyph for a host-catalog id directly (popup option rows), cached.
const idGlyphCache = new Map();
function glyphForCatalog(textId) {
  const n = Number(textId);
  const str = (n >= CATALOG_BASE && n - CATALOG_BASE < CATALOG.length) ? CATALOG[n - CATALOG_BASE] : String(n);
  if (!idGlyphCache.has(str)) idGlyphCache.set(str, sdfTexture(str));
  return idGlyphCache.get(str);
}

function render() {
  // Resolve geometry first: the arrange pass positions stack children (HStack/
  // VStack); absolute nodes keep their own x/y. Widgets then read laid-out coords
  // via r.attr transparently. (Recomputed each frame; dirty-tracking is a follow-up.)
  layoutMap = computeLayout(scene, renderCtx);
  // Content height = the lowest node bottom (absolute, pre-scroll); clamp scroll.
  contentH = 0;
  for (const rc of layoutMap.values()) contentH = Math.max(contentH, rc.y + rc.h);
  const cv = document.getElementById('gpu'); viewportH = cv ? cv.clientHeight : 0;
  const maxScroll = Math.max(0, contentH + 16 - viewportH);   // 16px bottom margin
  scrollY = Math.max(0, Math.min(scrollY, maxScroll));
  const frame = beginFrame(THEME.bg);
  renderCtx.pass = frame.pass;
  walk(ROOT);
  // Overlays last, on top of everything: the open menu or context menu (shared
  // popup primitive). Both get the viewport so they flip/clamp near edges.
  const spec = contextSpec ? withViewport(contextSpec) : openMenuSpec();
  if (spec) drawMenu(spec, renderCtx);
  endFrame(frame);
}
function walk(id) {
  const n = nodes.get(id); if (!n) return;
  if (id !== ROOT) {
    const w = widgetFor(n.kind);
    if (w && w.draw) w.draw(n, renderCtx);
    else if (id !== ROOT) { /* unknown/undrawn kind: skip (e.g. pure layout in Stage 1) */ }
  }
  for (const c of n.children) walk(c);
}

// ---- input: hit-test the tree, fire the wired handler via on_event -----------
function hitTest(px, py) {
  // Topmost-first: later children draw over earlier; walk in reverse.
  let found = null;
  const visit = (id) => {
    const n = nodes.get(id); if (!n) return;
    for (let i = n.children.length - 1; i >= 0; i--) visit(n.children[i]);
    if (found) return;
    if (id !== ROOT) {
      const w = widgetFor(n.kind);
      if (w && w.hit && w.hit(n, px, py, renderCtx)) found = n;
    }
  };
  visit(ROOT);
  return found;
}

function dispatch(node, event, payload = 0) {
  // Find the handler for this event; if the node has no handler for this exact
  // event (e.g. a slider wired to `press` but we're sending `input` during a
  // drag), fall back to its single registered handler. A Stage-1 control wires
  // exactly one handler, so this routes drag/input to it without the producer
  // having to wire every event id.
  let handler = node.handlers.get(event);
  if (handler === undefined) {
    if (node.handlers.size === 1) handler = node.handlers.values().next().value;
    else return;
  }
  // Stage-1 dispatch (spec/qview-protocol.md §Events). The wasm handler reads
  // state, mutates the exact node(s), and calls present(). Two shapes, in order:
  //   1. per-handler export `on_<id>` (the handler id from qview.on) — branchless,
  //      one export per wired control; what the compiler emits cleanly today.
  //   2. single dispatcher `on_event(node, event)` — fallback when no on_<id>.
  // All take (node, event, payload) i64 args: `payload` is a widget-computed
  // value (e.g. a slider's value from the touch position) — the event-payload
  // shape from the spec. Handlers that ignore it just take fewer params.
  const perHandler = instance.exports[`on_${handler}`];
  const fn = typeof perHandler === 'function' ? perHandler : instance.exports.on_event;
  if (typeof fn === 'function') fn(BigInt(node.id), BigInt(event), BigInt(Math.trunc(payload)));
  else log(`wasm exports no on_${handler} or on_event`);
}

async function main() {
  // Stamp the build into the header so you can confirm you're on the latest
  // deploy (regenerated by the build step; falls back to 'dev' locally).
  const hdr = document.querySelector('header');
  if (hdr) hdr.textContent = `QView · retained · build ${BUILD}`;

  // Fully suppress the browser's default touch/gesture behaviour — the app owns
  // every gesture. Block iOS pinch-zoom (gesturestart), the page context menu,
  // and double-tap-zoom (a fast second tap). CSS handles scroll/callout/select.
  document.addEventListener('gesturestart', (e) => e.preventDefault());
  document.addEventListener('gesturechange', (e) => e.preventDefault());
  document.addEventListener('contextmenu', (e) => e.preventDefault());
  let lastTouchEnd = 0;
  document.addEventListener('touchend', (e) => {
    const now = Date.now();
    if (now - lastTouchEnd < 300) e.preventDefault();   // kill double-tap zoom
    lastTouchEnd = now;
  }, { passive: false });

  const canvas = document.getElementById('gpu');
  const resize = () => { canvas.width = Math.round(canvas.clientWidth * DPR); canvas.height = Math.round(canvas.clientHeight * DPR); };
  try { await initGPU(canvas); }
  catch (e) { log('WebGPU unavailable: ' + e.message + ' — open in a WebGPU-capable browser (iPad Safari 18+).'); return; }
  resize();

  const resp = await fetch('./screen.wasm');
  const bytes = await resp.arrayBuffer();
  const { instance: inst } = await WebAssembly.instantiate(bytes, ops());
  instance = inst;
  log(`retained host v${PROTOCOL_VERSION} · wasm32 (${bytes.byteLength} B) · WebGPU`);

  instance.exports._start();   // builds the retained tree + first present()

  // Pin the translucent top bar (+ its title) so it stays fixed while content
  // scrolls beneath it. (The gallery's bar is nodes 90/91.) Everything else is in
  // screen space already (r.attr subtracts scrollY), so hit-tests + the existing
  // pointer math need no change — only scrollY moves.
  for (const id of [90, 91]) { const n = nodes.get(id); if (n) n._pinned = true; }

  // A widget may expose value(node, px, py, r) -> i64 to turn a touch position
  // into a payload (e.g. a slider's value). If it does, the control is also
  // DRAGGABLE: we track the pointer and re-dispatch as it moves, so the thumb
  // follows the finger (EVENT.input during drag, EVENT.change implied on press).
  let dragNode = null, scrollDrag = null;

  const localXY = (ev) => { const r = canvas.getBoundingClientRect(); return [ev.clientX - r.left, ev.clientY - r.top]; };

  // ---- scroll momentum (inertia) ----------------------------------------------
  // On release, the scroll keeps gliding at the finger's last velocity and decays
  // exponentially (iOS-like). A drag/wheel/tap cancels any running glide.
  let momentum = 0;            // px/frame velocity
  let momentumRAF = 0;
  const FRICTION = 0.94;       // per-frame decay (higher = longer glide)
  const MIN_V = 0.4;           // stop below this speed
  const maxScroll = () => Math.max(0, contentH + 16 - viewportH);
  function stopMomentum() { if (momentumRAF) { cancelAnimationFrame(momentumRAF); momentumRAF = 0; } momentum = 0; }
  function startMomentum(v0) {
    stopMomentum();
    momentum = v0;
    const step = () => {
      momentum *= FRICTION;
      scrollY += momentum;
      // Stop at the edges (no rubber-band overshoot — render() clamps scrollY).
      const m = maxScroll();
      if (scrollY <= 0 || scrollY >= m) { scrollY = Math.max(0, Math.min(scrollY, m)); render(); stopMomentum(); return; }
      render();
      if (Math.abs(momentum) < MIN_V) { stopMomentum(); return; }
      momentumRAF = requestAnimationFrame(step);
    };
    momentumRAF = requestAnimationFrame(step);
  }

  // Long-press (touch) / right-click (mouse) -> a context menu anchored at the
  // point, for any node whose widget exposes contextMenu(node, r). Reuses the
  // shared popup primitive (so it flips/clamps near edges too).
  const LONG_PRESS_MS = 500;
  const LONG_PRESS_SLOP = 10;   // px the finger may wobble during a hold
  let longPressTimer = null, longPressFired = false, longPressXY = null;
  const cancelLongPress = () => { if (longPressTimer) { clearTimeout(longPressTimer); longPressTimer = null; } longPressXY = null; };

  // Open a context menu for the node at (px,py), anchored at the point. Returns
  // true if a menu was raised.
  function openContextMenu(px, py) {
    const hit = hitTest(px, py);
    const w = hit && widgetFor(hit.kind);
    if (!w || !w.contextMenu) return false;
    const cm = w.contextMenu(hit, renderCtx);
    if (!cm || !cm.items || cm.items.length === 0) return false;
    contextSpec = { anchor: { x: px, y: py, w: 0, h: 0 }, items: cm.items, width: cm.width ?? 200 };
    contextNode = hit;
    render();
    return true;
  }

  canvas.addEventListener('pointerdown', (ev) => {
    stopMomentum();                              // a new touch halts any scroll glide
    const [px, py] = localXY(ev);

    // If a menu is open, it captures this tap first (shared popup primitive):
    // pick an item (-> selection payload to the wasm) or dismiss on an outside tap.
    if (openDropdownId !== null || contextSpec) {
      const spec = contextSpec ? withViewport(contextSpec) : openMenuSpec();
      const target = contextSpec ? contextNode : nodes.get(openDropdownId);
      const chosen = hitMenu(spec, px, py);
      openDropdownId = null; contextSpec = null; contextNode = null;
      if (chosen !== null && chosen !== undefined && target) {
        dispatch(target, EVENT.change, chosen);     // wasm updates the field/selection
        // The platform dropdown re-themes the whole gallery live (iOS/Material/…).
        if (OPTION_PLATFORM[chosen]) setPlatform(OPTION_PLATFORM[chosen]);
      } else render();
      return;
    }

    const hit = hitTest(px, py);
    const w = hit && widgetFor(hit.kind);

    // No interactive target under the finger -> arm a SCROLL drag (when content
    // overflows the viewport). A vertical drag on empty space / a label scrolls.
    if (!w || (!w.hit && !w.value && !w.menuSpec && !w.contextMenu)) {
      if (contentH + 16 > viewportH) {
        scrollDrag = { startY: py, startScroll: scrollY, moved: false };
        try { canvas.setPointerCapture(ev.pointerId); } catch {}
      }
      return;
    }

    // Arm long-press if this node has a context menu (touch raises it after a hold).
    if (w && w.contextMenu) {
      longPressFired = false;
      cancelLongPress();
      longPressXY = [px, py];
      longPressTimer = setTimeout(() => { longPressTimer = null; longPressFired = openContextMenu(px, py); }, LONG_PRESS_MS);
    }
    // A widget that can raise a menu (dropdown): toggle it open.
    if (w && w.menuSpec) {
      openDropdownId = hit.id;
      render();
      return;
    }
    if (w && typeof w.value === 'function') {
      // Ranged control: set value to where you touched (down = jump-to), and arm
      // dragging so the thumb tracks the finger. preventDefault + pointer capture
      // keep the whole drag ours (no scroll-steal when it drifts vertically).
      ev.preventDefault();
      dragNode = hit;
      try { canvas.setPointerCapture(ev.pointerId); } catch {}
      dispatch(hit, EVENT.input, w.value(hit, px, py, renderCtx));
      return;
    }
    // A context-menu-only node (no press handler) waits for the long-press; don't
    // flash a press for it.
    if (w && w.contextMenu && !(hit.handlers && hit.handlers.size)) return;
    pressedId = hit.id; render();                       // immediate pressed-state flash
    dispatch(hit, EVENT.press);                         // wasm mutates + presents
    setTimeout(() => { pressedId = null; render(); }, 120);
  }, { passive: false });

  canvas.addEventListener('pointermove', (ev) => {
    // Scroll drag: translate the scene by the finger's vertical delta, tracking
    // velocity (last-frame px delta) so release can launch momentum.
    if (scrollDrag) {
      ev.preventDefault();
      const [, py] = localXY(ev);
      const dy = py - scrollDrag.startY;
      if (Math.abs(dy) > 4) scrollDrag.moved = true;
      const prev = scrollY;
      scrollY = scrollDrag.startScroll - dy;            // drag down -> content moves down
      scrollDrag.vel = scrollY - prev;                  // px since last move = velocity
      render();                                          // render() clamps scrollY
      return;
    }
    // Cancel a pending long-press only if the finger moves beyond the slop radius
    // (a real hold always wobbles a few px; a true drag/scroll exceeds slop).
    if (longPressTimer && longPressXY) {
      const [sx, sy] = longPressXY;
      const [mx, my] = localXY(ev);
      if (Math.hypot(mx - sx, my - sy) > LONG_PRESS_SLOP) cancelLongPress();
    }
    if (!dragNode) return;
    ev.preventDefault();
    // Only the x drives the value; vertical drift (e.g. toward a label) is
    // ignored, so the drag holds anywhere on the canvas once captured.
    const [px, py] = localXY(ev);
    const w = widgetFor(dragNode.kind);
    dispatch(dragNode, EVENT.input, w.value(dragNode, px, py, renderCtx));
  }, { passive: false });

  const endDrag = (ev) => {
    cancelLongPress();                          // a lift before the hold elapsed = a tap, not long-press
    if (scrollDrag) {
      try { canvas.releasePointerCapture(ev.pointerId); } catch {}
      const v = scrollDrag.vel || 0;
      scrollDrag = null;
      if (Math.abs(v) > 1) startMomentum(v);    // flick -> glide
      return;
    }
    if (!dragNode) return;
    try { canvas.releasePointerCapture(ev.pointerId); } catch {}
    dragNode = null;
  };
  canvas.addEventListener('pointerup', endDrag);
  canvas.addEventListener('pointercancel', endDrag);

  // Wheel / trackpad scroll (desktop).
  canvas.addEventListener('wheel', (ev) => {
    if (contentH + 16 <= viewportH) return;
    ev.preventDefault();
    stopMomentum();
    scrollY += ev.deltaY;
    render();                                    // clamps
  }, { passive: false });

  // Right-click (desktop) -> the same context menu, anchored at the pointer.
  canvas.addEventListener('contextmenu', (ev) => {
    ev.preventDefault();                        // suppress the browser menu
    const [px, py] = localXY(ev);
    // Dismiss any open menu first; then raise the context menu (if any) here.
    openDropdownId = null; contextSpec = null; contextNode = null;
    if (!openContextMenu(px, py)) render();
  });

  window.addEventListener('resize', () => { resize(); render(); });
}
main();
