// QView Stage-1 RETAINED host (WebGPU). spec/qview-protocol.md.
//
// Unlike the immediate-mode POC (runtime/web/app.js), this host keeps a RETAINED
// node tree (node_id -> record). The wasm builds it once via create/set_attr/on,
// then mutates it surgically from the on_event dispatcher. present() re-encodes
// the current tree. Node identity (and thus future focus/caret/scroll) is the
// node_id, preserved across frames — never a blind full re-emit.
import { KIND, ATTR, EVENT, EVENT_NAME, SURFACE, unpackColor, PROTOCOL_VERSION } from './protocol.js';

// Build stamp (date + sha), regenerated by the build step. Dynamically imported
// with a fallback so a fresh checkout without a build still loads (version.js is
// a gitignored artifact, always present in a built/deployed bundle).
let BUILD = 'dev';
try { ({ BUILD } = await import('./version.js')); } catch {}
import { initGPU, drawPrim, sdfTexture, beginFrame, endFrame, DPR } from './gpu.js';
import { drawPopup as drawMenu, hitPopup as hitMenu } from './popup.js';
import { widgetFor } from './widgets.js';
import { resolvePlatform } from './platform.js';
import { themeFor } from './theme.js';

// One self-drawn renderer, three looks: iOS-ish on iOS, Material-ish on Android,
// a neutral house look on desktop. The platform is resolved once (sniff +
// ?platform= override); the per-platform theme tokens flow to every widget via
// r.platform / r.theme. Shaders and the protocol are unchanged — only tokens and
// (for structurally-different controls) per-platform draw variants differ.
const PLATFORM = resolvePlatform();
const THEME = themeFor(PLATFORM);

const log = (m) => { const el = document.getElementById('log'); if (el) el.textContent = m; console.log('[qview]', m); };

// Host-owned glyph catalog (Stage-1 text-by-id; no strings cross wasm). A label
// whose text_id < CATALOG.length shows that string; otherwise the id is rendered
// as an integer (the POC's `number` path — live counters etc.).
const CATALOG = [
  'Widget gallery',  // 0
  'Label',           // 1
  'Button',          // 2
  'Checkbox',        // 3
  'Switch',          // 4
  'Radio A',         // 5
  'Radio B',         // 6
  'Slider',          // 7
  'Progress',        // 8
  'Dropdown',        // 9  (the row's name label)
  'Box',             // 10
  'Tap +1',          // 11
  'iOS',             // 12  dropdown options (selected value shows in the field)
  'Android',         // 13
  'Windows',         // 14
  'Linux',           // 15
  'Grouped',         // 16  group heading
  'In a group',      // 17  group sub-label
  'Long Click',      // 18  the context-menu touch area title
  'Cut',             // 19  context-menu items
  'Copy',            // 20
  'Paste',           // 21
];

// ---- the retained tree -------------------------------------------------------
// id -> { id, kind, parent, attrs:Map<attr,i64>, children:[id], handlers:Map<event,handlerId> }
const nodes = new Map();
const ROOT = 0;
nodes.set(ROOT, { id: ROOT, kind: -1, parent: -1, attrs: new Map(), children: [], handlers: new Map() });

let glyphCache = new Map();  // nodeId -> {tex,view,w,h}; rebuilt only when text changes
let glyphKey = new Map();    // nodeId -> last text string used, to skip rebuilds
let pressedId = null;
let pendingMuts = [];        // mutation log for the current frame (diagnostics)
let instance;

function textStringFor(node) {
  const id = node.attrs.get(ATTR.text_id);
  if (id === undefined) return null;
  const n = Number(id);
  return (n >= 0 && n < CATALOG.length) ? CATALOG[n] : String(n);
}
function glyphFor(node) {
  const str = textStringFor(node);
  if (str === null) return null;
  if (glyphKey.get(node.id) !== str) {           // surgical: only a changed text re-rasterizes
    glyphCache.set(node.id, sdfTexture(str));
    glyphKey.set(node.id, str);
  }
  return glyphCache.get(node.id);
}

// ---- the five ops (the wasm import face) ------------------------------------
function ops() {
  return {
    env: { out: () => {} },
    qview: {
      create: (id, kind, parent) => {
        id = Number(id); kind = Number(kind); parent = Number(parent);
        if (nodes.has(id)) { const n = nodes.get(id); if (n.kind !== kind) log(`proto error: create #${id} kind conflict`); return; }
        const p = nodes.get(parent) ?? nodes.get(ROOT);
        const node = { id, kind, parent: p.id, attrs: new Map(), children: [], handlers: new Map() };
        nodes.set(id, node); p.children.push(id);
        pendingMuts.push(`create #${id} ${kindName(kind)}`);
      },
      set_attr: (id, attr, value) => {
        const n = nodes.get(Number(id)); if (!n) { log(`proto error: set_attr on unknown #${id}`); return; }
        n.attrs.set(Number(attr), value);            // keep raw i64 (BigInt); readers Number()/unpack
        pendingMuts.push(`set_attr #${Number(id)} ${attrName(attr)}`);
        glyphKey.delete(Number(id));                 // text may have changed; force re-eval on draw
      },
      remove: (id) => {
        id = Number(id); const n = nodes.get(id); if (!n) return;
        removeSubtree(id);
        pendingMuts.push(`remove #${id}`);
      },
      on: (id, event, handler) => {
        const n = nodes.get(Number(id)); if (!n) return;
        if (Number(handler) === 0) n.handlers.delete(Number(event));
        else n.handlers.set(Number(event), Number(handler));
      },
      present: () => { render(); if (pendingMuts.length) { log('mutate: ' + pendingMuts.join(', ')); pendingMuts = []; } },
    },
  };
}

function removeSubtree(id) {
  const n = nodes.get(id); if (!n) return;
  for (const c of [...n.children]) removeSubtree(c);
  const p = nodes.get(n.parent); if (p) p.children = p.children.filter((c) => c !== id);
  nodes.delete(id); glyphCache.delete(id); glyphKey.delete(id);
}

const kindName = (k) => Object.keys(KIND).find((n) => KIND[n] === k) ?? `kind${k}`;
const attrName = (a) => Object.keys(ATTR).find((n) => ATTR[n] === a) ?? `attr${a}`;

// ATTR.surface role tag -> theme token key (the translucent material fills).
const SURFACE_KEY = { [SURFACE.none]: 'none', [SURFACE.surface]: 'surface', [SURFACE.material]: 'material', [SURFACE.materialThin]: 'materialThin', [SURFACE.scrim]: 'scrim' };

// ---- render: walk the retained tree, dispatch each node to its widget --------
const renderCtx = {
  pass: null, drawPrim, sdfText: sdfTexture, theme: THEME, platform: PLATFORM,
  attr: (node, a, dflt) => { const v = node.attrs.get(a); return v === undefined ? dflt : Number(v); },
  color: (node, a, dflt) => { const v = node.attrs.get(a); return v === undefined ? dflt : unpackColor(v); },
  // Resolve a node's fill, honoring a semantic ATTR.surface role (theme-resolved
  // translucent material) over a literal ATTR.fill over the given default.
  surfaceFill: (node, dflt) => {
    const role = node.attrs.get(ATTR.surface);
    if (role !== undefined) {
      const key = SURFACE_KEY[Number(role)];
      if (key && key !== 'none') return THEME[key] ?? dflt;
      if (key === 'none') return null;
    }
    const lit = node.attrs.get(ATTR.fill);
    return lit === undefined ? dflt : unpackColor(lit);
  },
  textFor: (node) => glyphFor(node),
  glyphForId: (textId) => glyphForCatalog(textId),
  isPressed: (id) => id === pressedId,
  isOpen: (id) => id === openDropdownId,
};

// The node currently showing a menu (one open at a time), or null. Any widget
// exposing menuSpec(node, r) can raise the shared popup; today that's the
// dropdown, tomorrow a context menu.
let openDropdownId = null;
// A context menu (long-press / right-click) raised at a point: its popup spec +
// the node it belongs to. Separate from openDropdownId (anchored differently).
let contextSpec = null, contextNode = null;

// The menu spec for the currently-open node (or null) — built fresh each use so
// it reflects current selection/geometry. The host injects the viewport (CSS px)
// so the popup can flip/clamp to stay on-screen.
function openMenuSpec() {
  if (openDropdownId === null) return null;
  const n = nodes.get(openDropdownId);
  const w = n && widgetFor(n.kind);
  if (!w || !w.menuSpec) return null;
  return withViewport(w.menuSpec(n, renderCtx));
}

// Inject the viewport (CSS px) into a popup spec so it can flip/clamp on-screen.
function withViewport(spec) {
  if (spec) {
    const cv = document.getElementById('gpu');
    if (cv) spec.viewport = { w: cv.clientWidth, h: cv.clientHeight };
  }
  return spec;
}

// A glyph for a host-catalog id directly (popup option rows), cached.
const idGlyphCache = new Map();
function glyphForCatalog(textId) {
  const n = Number(textId);
  const str = (n >= 0 && n < CATALOG.length) ? CATALOG[n] : String(n);
  if (!idGlyphCache.has(str)) idGlyphCache.set(str, sdfTexture(str));
  return idGlyphCache.get(str);
}

function render() {
  const frame = beginFrame(THEME.bg);
  renderCtx.pass = frame.pass;
  walk(ROOT);
  // Overlays last, on top of everything: the open menu or context menu (shared
  // popup primitive). Both get the viewport so they flip/clamp near edges.
  const spec = contextSpec ? withViewport(contextSpec) : openMenuSpec();
  if (spec) drawMenu(spec, renderCtx);
  endFrame(frame);
}
function walk(id) {
  const n = nodes.get(id); if (!n) return;
  if (id !== ROOT) {
    const w = widgetFor(n.kind);
    if (w && w.draw) w.draw(n, renderCtx);
    else if (id !== ROOT) { /* unknown/undrawn kind: skip (e.g. pure layout in Stage 1) */ }
  }
  for (const c of n.children) walk(c);
}

// ---- input: hit-test the tree, fire the wired handler via on_event -----------
function hitTest(px, py) {
  // Topmost-first: later children draw over earlier; walk in reverse.
  let found = null;
  const visit = (id) => {
    const n = nodes.get(id); if (!n) return;
    for (let i = n.children.length - 1; i >= 0; i--) visit(n.children[i]);
    if (found) return;
    if (id !== ROOT) {
      const w = widgetFor(n.kind);
      if (w && w.hit && w.hit(n, px, py, renderCtx)) found = n;
    }
  };
  visit(ROOT);
  return found;
}

function dispatch(node, event, payload = 0) {
  // Find the handler for this event; if the node has no handler for this exact
  // event (e.g. a slider wired to `press` but we're sending `input` during a
  // drag), fall back to its single registered handler. A Stage-1 control wires
  // exactly one handler, so this routes drag/input to it without the producer
  // having to wire every event id.
  let handler = node.handlers.get(event);
  if (handler === undefined) {
    if (node.handlers.size === 1) handler = node.handlers.values().next().value;
    else return;
  }
  // Stage-1 dispatch (spec/qview-protocol.md §Events). The wasm handler reads
  // state, mutates the exact node(s), and calls present(). Two shapes, in order:
  //   1. per-handler export `on_<id>` (the handler id from qview.on) — branchless,
  //      one export per wired control; what the compiler emits cleanly today.
  //   2. single dispatcher `on_event(node, event)` — fallback when no on_<id>.
  // All take (node, event, payload) i64 args: `payload` is a widget-computed
  // value (e.g. a slider's value from the touch position) — the event-payload
  // shape from the spec. Handlers that ignore it just take fewer params.
  const perHandler = instance.exports[`on_${handler}`];
  const fn = typeof perHandler === 'function' ? perHandler : instance.exports.on_event;
  if (typeof fn === 'function') fn(BigInt(node.id), BigInt(event), BigInt(Math.trunc(payload)));
  else log(`wasm exports no on_${handler} or on_event`);
}

async function main() {
  // Stamp the build into the header so you can confirm you're on the latest
  // deploy (regenerated by the build step; falls back to 'dev' locally).
  const hdr = document.querySelector('header');
  if (hdr) hdr.textContent = `QView · retained · build ${BUILD}`;

  const canvas = document.getElementById('gpu');
  const resize = () => { canvas.width = Math.round(canvas.clientWidth * DPR); canvas.height = Math.round(canvas.clientHeight * DPR); };
  try { await initGPU(canvas); }
  catch (e) { log('WebGPU unavailable: ' + e.message + ' — open in a WebGPU-capable browser (iPad Safari 18+).'); return; }
  resize();

  const resp = await fetch('./screen.wasm');
  const bytes = await resp.arrayBuffer();
  const { instance: inst } = await WebAssembly.instantiate(bytes, ops());
  instance = inst;
  log(`retained host v${PROTOCOL_VERSION} · wasm32 (${bytes.byteLength} B) · WebGPU`);

  instance.exports._start();   // builds the retained tree + first present()

  // A widget may expose value(node, px, py, r) -> i64 to turn a touch position
  // into a payload (e.g. a slider's value). If it does, the control is also
  // DRAGGABLE: we track the pointer and re-dispatch as it moves, so the thumb
  // follows the finger (EVENT.input during drag, EVENT.change implied on press).
  let dragNode = null;

  const localXY = (ev) => { const r = canvas.getBoundingClientRect(); return [ev.clientX - r.left, ev.clientY - r.top]; };

  // Long-press (touch) / right-click (mouse) -> a context menu anchored at the
  // point, for any node whose widget exposes contextMenu(node, r). Reuses the
  // shared popup primitive (so it flips/clamps near edges too).
  const LONG_PRESS_MS = 500;
  let longPressTimer = null, longPressFired = false;
  const cancelLongPress = () => { if (longPressTimer) { clearTimeout(longPressTimer); longPressTimer = null; } };

  // Open a context menu for the node at (px,py), anchored at the point. Returns
  // true if a menu was raised.
  function openContextMenu(px, py) {
    const hit = hitTest(px, py);
    const w = hit && widgetFor(hit.kind);
    if (!w || !w.contextMenu) return false;
    const cm = w.contextMenu(hit, renderCtx);
    if (!cm || !cm.items || cm.items.length === 0) return false;
    contextSpec = { anchor: { x: px, y: py, w: 0, h: 0 }, items: cm.items, width: cm.width ?? 200 };
    contextNode = hit;
    render();
    return true;
  }

  canvas.addEventListener('pointerdown', (ev) => {
    const [px, py] = localXY(ev);

    // If a menu is open, it captures this tap first (shared popup primitive):
    // pick an item (-> selection payload to the wasm) or dismiss on an outside tap.
    if (openDropdownId !== null || contextSpec) {
      const spec = contextSpec ? withViewport(contextSpec) : openMenuSpec();
      const target = contextSpec ? contextNode : nodes.get(openDropdownId);
      const chosen = hitMenu(spec, px, py);
      openDropdownId = null; contextSpec = null; contextNode = null;
      if (chosen !== null && chosen !== undefined && target) dispatch(target, EVENT.change, chosen);
      else render();
      return;
    }

    const hit = hitTest(px, py);
    if (!hit) return;
    const w = widgetFor(hit.kind);

    // Arm long-press if this node has a context menu (touch raises it after a hold).
    if (w && w.contextMenu) {
      longPressFired = false;
      cancelLongPress();
      longPressTimer = setTimeout(() => { longPressTimer = null; longPressFired = openContextMenu(px, py); }, LONG_PRESS_MS);
    }
    // A widget that can raise a menu (dropdown): toggle it open.
    if (w && w.menuSpec) {
      openDropdownId = hit.id;
      render();
      return;
    }
    if (w && typeof w.value === 'function') {
      // Ranged control: set value to where you touched (down = jump-to), and arm
      // dragging so the thumb tracks the finger. preventDefault + pointer capture
      // keep the whole drag ours (no scroll-steal when it drifts vertically).
      ev.preventDefault();
      dragNode = hit;
      try { canvas.setPointerCapture(ev.pointerId); } catch {}
      dispatch(hit, EVENT.input, w.value(hit, px, py, renderCtx));
      return;
    }
    // A context-menu-only node (no press handler) waits for the long-press; don't
    // flash a press for it.
    if (w && w.contextMenu && !(hit.handlers && hit.handlers.size)) return;
    pressedId = hit.id; render();                       // immediate pressed-state flash
    dispatch(hit, EVENT.press);                         // wasm mutates + presents
    setTimeout(() => { pressedId = null; render(); }, 120);
  }, { passive: false });

  canvas.addEventListener('pointermove', (ev) => {
    // A finger that moves cancels a pending long-press (it's a drag/scroll, not a hold).
    if (longPressTimer) cancelLongPress();
    if (!dragNode) return;
    ev.preventDefault();
    // Only the x drives the value; vertical drift (e.g. toward a label) is
    // ignored, so the drag holds anywhere on the canvas once captured.
    const [px, py] = localXY(ev);
    const w = widgetFor(dragNode.kind);
    dispatch(dragNode, EVENT.input, w.value(dragNode, px, py, renderCtx));
  }, { passive: false });

  const endDrag = (ev) => {
    cancelLongPress();                          // a lift before the hold elapsed = a tap, not long-press
    if (!dragNode) return;
    try { canvas.releasePointerCapture(ev.pointerId); } catch {}
    dragNode = null;
  };
  canvas.addEventListener('pointerup', endDrag);
  canvas.addEventListener('pointercancel', endDrag);

  // Right-click (desktop) -> the same context menu, anchored at the pointer.
  canvas.addEventListener('contextmenu', (ev) => {
    ev.preventDefault();                        // suppress the browser menu
    const [px, py] = localXY(ev);
    // Dismiss any open menu first; then raise the context menu (if any) here.
    openDropdownId = null; contextSpec = null; contextNode = null;
    if (!openContextMenu(px, py)) render();
  });

  window.addEventListener('resize', () => { resize(); render(); });
}
main();
