// QView Stage-1 RETAINED host (WebGPU). spec/qview-protocol.md.
//
// Unlike the immediate-mode POC (runtime/web/app.js), this host keeps a RETAINED
// node tree (node_id -> record). The wasm builds it once via create/set_attr/on,
// then mutates it surgically from the on_event dispatcher. present() re-encodes
// the current tree. Node identity (and thus future focus/caret/scroll) is the
// node_id, preserved across frames — never a blind full re-emit.
import { KIND, ATTR, EVENT, EVENT_NAME, SURFACE, TEXTKEY, unpackColor, PROTOCOL_VERSION } from './protocol.js';

// Build stamp (date + sha), regenerated by the build step. Dynamically imported
// with a fallback so a fresh checkout without a build still loads (version.js is
// a gitignored artifact, always present in a built/deployed bundle).
let BUILD = 'dev';
try { ({ BUILD } = await import('./version.js')); } catch {}
// Snap upload config (api origin + snap:create token), filled by the deploy.
let SNAP = { api: '', token: '' };
try { ({ SNAP } = await import('./snap-config.js')); } catch {}
import { initGPU, drawPrim, sdfTexture, beginFrame, endFrame, setScissor, DPR } from './gpu.js';
import { drawPopup as drawMenu, hitPopup as hitMenu } from './popup.js';
import { widgetFor } from './widgets.js';
import { Scene } from './scene.js';
import { computeLayout } from './arrange.js';
import { resolvePlatform } from './platform.js';
import { themeFor } from './theme.js';

// One self-drawn renderer, three looks: iOS-ish on iOS, Material-ish on Android,
// a neutral house look on desktop. The platform is resolved once (sniff +
// ?platform= override); the per-platform theme tokens flow to every widget via
// r.platform / r.theme. Shaders and the protocol are unchanged — only tokens and
// (for structurally-different controls) per-platform draw variants differ.
// Mutable so the platform dropdown can RE-THEME the gallery live (pick Android ->
// Material). Starts from device detection / ?platform=; setPlatform() swaps it.
let PLATFORM = resolvePlatform();
let THEME = themeFor(PLATFORM);
// Catalog id of a platform option (1012..1015) -> theme platform key.
const OPTION_PLATFORM = { 1012: 'ios', 1013: 'android', 1014: 'desktop', 1015: 'desktop' };
function setPlatform(p) {
  if (!p || p === PLATFORM) return;
  PLATFORM = p; THEME = themeFor(p);
  // Live-update both contexts; theme can change control sizes (switch variant),
  // so relayout then render.
  renderCtx.theme = THEME; renderCtx.platform = PLATFORM;
  layoutCtx.theme = THEME; layoutCtx.platform = PLATFORM;
  layout();
  render();
}

const log = (m) => { const el = document.getElementById('log'); if (el) el.textContent = m; console.log('[qview]', m); };

// Host-owned glyph catalog (Stage-1 text-by-id; no strings cross wasm). A label
// whose text_id < CATALOG.length shows that string; otherwise the id is rendered
// as an integer (the POC's `number` path — live counters etc.).
const CATALOG_BASE = 1000;  // catalog ids are 1000+, so small ints render as numbers
const CATALOG = [
  'Widget gallery',  // 0
  'Label',           // 1
  'Button',          // 2
  'Checkbox',        // 3
  'Switch',          // 4
  'Radio A',         // 5
  'Radio B',         // 6
  'Slider',          // 7
  'Progress',        // 8
  'Dropdown',        // 9  (the row's name label)
  'Box',             // 10
  'Tap +1',          // 11
  'iOS',             // 12  dropdown options (selected value shows in the field)
  'Android',         // 13
  'Windows',         // 14
  'Linux',           // 15
  'Grouped',         // 16  group heading
  'In a group',      // 17  group sub-label
  'Long Click',      // 18  the context-menu touch area title
  'Cut',             // 19  context-menu items
  'Copy',            // 20
  'Paste',           // 21
  'Fader',           // 22
  'Meter',           // 23
  'Pan',             // 24
  'Volume',          // 25
  'Text input',      // 26  text field section label
  'type your name…', // 27  the field placeholder (set via set_text)
  'chars',           // 28  suffix after the live length
  'has @',           // 29  validation status: contains '@'
  'no @ yet',        // 30  validation status: missing '@'
];

// ---- the retained tree (generic, VALIDATED applier) --------------------------
// Scene owns the node tree + the five ops, schema-validating each before it
// touches the tree (spec §"Host obligations"). This host is one backend over it;
// the soft renderer is another. nodes/ROOT alias into the scene so the render +
// input code below reads unchanged.
const scene = new Scene({ onReject: (m) => log('drop: ' + m) });
const nodes = scene.nodes;
const ROOT = scene.ROOT;
// Evict glyph caches when the scene removes a node.
scene.onNodeRemoved = (id) => { glyphCache.delete(id); glyphKey.delete(id); };

let glyphCache = new Map();  // nodeId -> {tex,view,w,h}; rebuilt only when text changes
let glyphKey = new Map();    // nodeId -> last text string used, to skip rebuilds
let pressedId = null;
let focusedId = null;        // the text_input node id with keyboard focus, or null
let caretOn = true;          // caret blink phase (visible) while a field is focused
let blinkTimer = null;       // setInterval handle driving the blink
let kbScrolled = false;      // have we already lifted the focused field above the keyboard?
let instance;

// Host→app text scratch: when the user types, the host writes the field's UTF-8
// into wasm linear memory here and calls on_<id>(node, event, ptr, len) so the
// handler's `text: str` param points at it. A fixed high offset in the single
// 64 KB page — q64's static data + arena live low and never reach it for a UI
// handler (which doesn't allocate). Clamped to TEXT_CAP bytes.
const TEXT_BUF = 0xf000;
const TEXT_CAP = 0x800;

function textStringFor(node) {
  const id = node.attrs.get(ATTR.text_id);
  if (id === undefined) return null;
  const n = Number(id);
  // text_id >= CATALOG_BASE is a catalog string; below it is a literal integer
  // (e.g. a live counter), so 'show the number 0' never collides with CATALOG[0].
  return (n >= CATALOG_BASE && n - CATALOG_BASE < CATALOG.length) ? CATALOG[n - CATALOG_BASE] : String(n);
}
function glyphFor(node) {
  const str = textStringFor(node);
  if (str === null) return null;
  if (glyphKey.get(node.id) !== str) {           // surgical: only a changed text re-rasterizes
    glyphCache.set(node.id, sdfTexture(str));
    glyphKey.set(node.id, str);
  }
  return glyphCache.get(node.id);
}

// ---- the wasm import face: the validated Scene ops + a backend present() -----
// Scene.face wires create/set_attr/remove/on to the validated applier; present()
// is this backend's frame commit (render + drain the mutation log). A set_attr
// may change a node's text, so we evict its glyph key around the applier.
function ops() {
  const sceneFace = scene.face(() => {
    // present() = the tree just changed -> relayout (Phase 1) then render (Phase 2).
    layout();
    render();
    const m = scene.drainMuts();
    if (m.length) log('mutate: ' + m.join(', '));
  });
  return {
    env: { out: () => {} },
    qview: {
      ...sceneFace,
      set_attr: (id, attr, value) => { glyphKey.delete(Number(id)); sceneFace.set_attr(id, attr, value); },
      // A STRING op: the app passed (ptr, len) into wasm linear memory; read the
      // UTF-8 and stash it on the node under `key` (TEXTKEY: value | placeholder).
      // The text_input widget renders node._text; a changed string re-rasterizes
      // via the string-keyed glyph cache (no per-node invalidation needed).
      set_text: (id, key, ptr, len) => {
        const n = nodes.get(Number(id));
        if (!n) return;
        (n._text ??= {})[Number(key)] = readUtf8(ptr, len);
      },
    },
  };
}

// Decode a (ptr, len) span of the wasm instance's linear memory as UTF-8. Used
// by the string ops (set_text) and to read back validated/echoed text.
const decoder = new TextDecoder();
function readUtf8(ptr, len) {
  return decoder.decode(new Uint8Array(instance.exports.memory.buffer, Number(ptr), Number(len)));
}

// ATTR.surface role tag -> theme token key (the translucent material fills).
const SURFACE_KEY = { [SURFACE.none]: 'none', [SURFACE.surface]: 'surface', [SURFACE.material]: 'material', [SURFACE.materialThin]: 'materialThin', [SURFACE.scrim]: 'scrim' };

// ---- render: walk the retained tree, dispatch each node to its widget --------
// `layoutMap` (id -> {x,y,w,h}) holds resolved geometry from the arrange pass
// (stacks own their children's coords). When a node has a layout entry, r.attr
// returns its laid-out x/y/w/h transparently — widgets read geometry the same
// way whether they're absolute or inside an HStack/VStack.
let layoutMap = new Map();
const GEOM = { [ATTR.x]: 'x', [ATTR.y]: 'y', [ATTR.w]: 'w', [ATTR.h]: 'h' };
// Host-managed vertical scroll: the canvas stays viewport-sized; the whole scene
// is translated up by scrollY at draw time (and touches translated down to match),
// so content taller than the screen is reachable without native scroll fighting
// the slider/long-press gestures. The pinned top bar opts out (drawn unshifted).
let scrollY = 0, contentH = 0, viewportH = 0;
// Horizontal centering: when the viewport is wider than the content (iPad,
// landscape, desktop), shift everything right by offsetX so the UI sits centered
// instead of hugging the left. 0 on a phone where content == viewport width.
let offsetX = 0, contentW = 0;
const SCROLL_BOTTOM_PAD = 40;   // extra room past content so the last widget fully clears
// Soft-keyboard inset (CSS px): how much of the canvas the iOS/Android keyboard
// overlays while a text field is focused. Detected via visualViewport. It both
// extends the scroll range (so a bottom field can rise above the keyboard) and
// defines the visible region we scroll the focused field into.
let kbInset = 0;
// The true scroll limit. Includes kbInset so content can scroll up past the
// keyboard when one is open. Module-scoped so focus/keyboard logic can use it.
function maxBound() { return Math.max(0, contentH + SCROLL_BOTTOM_PAD + kbInset - viewportH); }
// Current keyboard inset from the visual viewport: the canvas area below the
// shrunken visible region. ~0 when no keyboard is up.
function viewportInset() {
  const vv = window.visualViewport;
  const cv = document.getElementById('gpu');
  if (!vv || !cv) return 0;
  const r = cv.getBoundingClientRect();
  return Math.max(0, r.top + cv.clientHeight - vv.height);
}
// Scroll the focused field above the keyboard (into the visible region). Called
// on focus and whenever the visual viewport changes (keyboard open/close).
function ensureFocusedVisible() {
  if (focusedId === null) return;
  const cv = document.getElementById('gpu');
  const rc = layoutMap.get(focusedId);
  if (!cv || !rc) return;
  kbInset = viewportInset();
  const visibleBottom = cv.clientHeight - kbInset;
  const fieldBottom = rc.y - scrollY + rc.h;     // field's on-screen bottom (canvas-local)
  const margin = 16;
  if (fieldBottom > visibleBottom - margin) {
    scrollY = Math.max(0, Math.min(scrollY + fieldBottom - (visibleBottom - margin), maxBound()));
  }
  render();
}
const renderCtx = {
  pass: null, drawPrim, sdfText: sdfTexture, theme: THEME, platform: PLATFORM,
  attr: (node, a, dflt) => {
    const g = GEOM[a]; const lay = g && layoutMap.get(node.id);
    let v = lay ? lay[g] : node.attrs.get(a);
    v = v === undefined ? dflt : Number(v);
    if (a === ATTR.y && !node._pinned) v -= scrollY;     // translate scene up
    if (a === ATTR.x) v += offsetX;                       // center horizontally
    return v;
  },
  color: (node, a, dflt) => { const v = node.attrs.get(a); return v === undefined ? dflt : unpackColor(v); },
  // Resolve a node's fill, honoring a semantic ATTR.surface role (theme-resolved
  // translucent material) over a literal ATTR.fill over the given default.
  surfaceFill: (node, dflt) => {
    const role = node.attrs.get(ATTR.surface);
    if (role !== undefined) {
      const key = SURFACE_KEY[Number(role)];
      if (key && key !== 'none') return THEME[key] ?? dflt;
      if (key === 'none') return null;
    }
    const lit = node.attrs.get(ATTR.fill);
    return lit === undefined ? dflt : unpackColor(lit);
  },
  textFor: (node) => glyphFor(node),
  glyphForId: (textId) => glyphForCatalog(textId),
  isPressed: (id) => id === pressedId,
  isOpen: (id) => id === openDropdownId,
  // --- text_input helpers (host owns the editable value) ---
  // The field's current value / placeholder strings (set via the set_text op).
  textValue: (node) => node._text?.[TEXTKEY.value] ?? '',
  textPlaceholder: (node) => node._text?.[TEXTKEY.placeholder] ?? '',
  isFocused: (id) => id === focusedId,
  caretVisible: () => caretOn,
  // An SDF for an arbitrary string, cached by (string + size) — for field text
  // that changes per keystroke (no per-node glyph slot).
  glyphForStr: (str, sizePx) => glyphForStr(str, sizePx),
};

// The LAYOUT context: a PURE view for the layout pass. Its attr reads raw node
// attrs (no layoutMap, no scroll) — layout is computing those rects, and must be
// independent of scroll/render state (SwiftUI keeps layout pure). Shares text
// measurement so a label/button can size to its glyph.
const layoutCtx = {
  theme: THEME, platform: PLATFORM,
  attr: (node, a, dflt) => { const v = node.attrs.get(a); return v === undefined ? dflt : Number(v); },
  textFor: (node) => glyphFor(node),
  glyphForId: (textId) => glyphForCatalog(textId),
};

// The node currently showing a menu (one open at a time), or null. Any widget
// exposing menuSpec(node, r) can raise the shared popup; today that's the
// dropdown, tomorrow a context menu.
let openDropdownId = null;
// A context menu (long-press / right-click) raised at a point: its popup spec +
// the node it belongs to. Separate from openDropdownId (anchored differently).
let contextSpec = null, contextNode = null;

// The menu spec for the currently-open node (or null) — built fresh each use so
// it reflects current selection/geometry. The host injects the viewport (CSS px)
// so the popup can flip/clamp to stay on-screen.
function openMenuSpec() {
  if (openDropdownId === null) return null;
  const n = nodes.get(openDropdownId);
  const w = n && widgetFor(n.kind);
  if (!w || !w.menuSpec) return null;
  return withViewport(w.menuSpec(n, renderCtx));
}

// Inject the viewport (CSS px) into a popup spec so it can flip/clamp on-screen.
function withViewport(spec) {
  if (spec) {
    const cv = document.getElementById('gpu');
    if (cv) spec.viewport = { w: cv.clientWidth, h: cv.clientHeight };
  }
  return spec;
}

// A glyph for a host-catalog id directly (popup option rows), cached.
const idGlyphCache = new Map();
function glyphForCatalog(textId) {
  const n = Number(textId);
  const str = (n >= CATALOG_BASE && n - CATALOG_BASE < CATALOG.length) ? CATALOG[n - CATALOG_BASE] : String(n);
  if (!idGlyphCache.has(str)) idGlyphCache.set(str, sdfTexture(str));
  return idGlyphCache.get(str);
}

// An SDF for an arbitrary string at a size, cached by "size:str". For text_input
// values, which change per keystroke and have no per-node glyph slot. Empty
// string → null (nothing to draw). Cache is unbounded but a UI types few strings.
const strGlyphCache = new Map();
function glyphForStr(str, sizePx = 17) {
  if (!str) return null;
  const key = `${sizePx}:${str}`;
  if (!strGlyphCache.has(key)) strGlyphCache.set(key, sdfTexture(str, sizePx));
  return strGlyphCache.get(key);
}

// ===========================================================================
// Phase 1 — LAYOUT (one pure pass, SwiftUI-style). Geometry only: measure +
// arrange the tree into resolved rects (layoutMap). No scroll, no GPU, no clip.
// Recomputed only when the tree changes (layout()), NOT every frame. Also derives
// the content height and the sticky-header band from the pure geometry.
// ===========================================================================
let headerH = 0;            // bottom of the pinned header band (layout space)
function layout() {
  layoutMap = computeLayout(scene, layoutCtx);
  contentH = 0; headerH = 0; contentW = 0;
  for (const [id, rc] of layoutMap) {
    contentH = Math.max(contentH, rc.y + rc.h);
    contentW = Math.max(contentW, rc.x + rc.w);
    const n = nodes.get(id);
    if (n && n._pinned) headerH = Math.max(headerH, rc.y + rc.h);
  }
}

// ===========================================================================
// Phase 2 — RENDER PATH (consumes the resolved geometry). Applies scroll as a
// draw-time translate, clips scrollable content below the sticky header, draws.
// The GPU host and the soft renderer are two such paths over the same layout.
// ===========================================================================
function render() {
  const cv = document.getElementById('gpu');
  viewportH = cv ? cv.clientHeight : 0;
  const viewportW = cv ? cv.clientWidth : 0;
  // Center the content block when the viewport is wider than it (iPad/desktop);
  // the layout was built left-anchored (x from 0), so this shifts the whole UI.
  offsetX = Math.max(0, Math.round((viewportW - contentW) / 2));
  // NB: scrollY is NOT hard-clamped here — it may sit slightly past the edges
  // during an iOS-style rubber-band overscroll; the drag applies resistance and
  // release springs it back (see settleScroll). maxBound() is the true limit.

  const frame = beginFrame(THEME.bg);
  renderCtx.pass = frame.pass;
  // Pass 1: scrollable (unpinned) content, clipped below the header band.
  if (headerH > 0) setScissor(frame.pass, { x: 0, y: headerH, w: 10000, h: Math.max(0, viewportH - headerH) });
  walk(ROOT, false);
  // Pass 2: pinned chrome (the sticky header), unclipped, on top.
  setScissor(frame.pass, null);
  if (headerH > 0) walk(ROOT, true);
  // Overlays last, on top of everything: the open menu or context menu (shared
  // popup primitive). Both get the viewport so they flip/clamp near edges.
  const spec = contextSpec ? withViewport(contextSpec) : openMenuSpec();
  if (spec) drawMenu(spec, renderCtx);
  endFrame(frame);
}
// walk with a `pinned` filter: false = draw only unpinned subtrees; true = only
// pinned nodes. A node's pinned-ness is inherited from its nearest pinned ancestor.
function walk(id, wantPinned, pinned = false) {
  const n = nodes.get(id); if (!n) return;
  const isPinned = pinned || !!n._pinned;
  if (id !== ROOT && isPinned === wantPinned) {
    const w = widgetFor(n.kind);
    if (w && w.draw) w.draw(n, renderCtx);
  }
  for (const c of n.children) walk(c, wantPinned, isPinned);
}

// ---- input: hit-test the tree, fire the wired handler via on_event -----------
function hitTest(px, py) {
  // Topmost-first: later children draw over earlier; walk in reverse.
  let found = null;
  const visit = (id) => {
    const n = nodes.get(id); if (!n) return;
    for (let i = n.children.length - 1; i >= 0; i--) visit(n.children[i]);
    if (found) return;
    if (id !== ROOT) {
      const w = widgetFor(n.kind);
      if (w && w.hit && w.hit(n, px, py, renderCtx)) found = n;
    }
  };
  visit(ROOT);
  return found;
}

function dispatch(node, event, payload = 0) {
  // Find the handler for this event; if the node has no handler for this exact
  // event (e.g. a slider wired to `press` but we're sending `input` during a
  // drag), fall back to its single registered handler. A Stage-1 control wires
  // exactly one handler, so this routes drag/input to it without the producer
  // having to wire every event id.
  let handler = node.handlers.get(event);
  if (handler === undefined) {
    if (node.handlers.size === 1) handler = node.handlers.values().next().value;
    else return;
  }
  // Stage-1 dispatch (spec/qview-protocol.md §Events). The wasm handler reads
  // state, mutates the exact node(s), and calls present(). Two shapes, in order:
  //   1. per-handler export `on_<id>` (the handler id from qview.on) — branchless,
  //      one export per wired control; what the compiler emits cleanly today.
  //   2. single dispatcher `on_event(node, event)` — fallback when no on_<id>.
  // All take (node, event, payload) i64 args: `payload` is a widget-computed
  // value (e.g. a slider's value from the touch position) — the event-payload
  // shape from the spec. Handlers that ignore it just take fewer params.
  const perHandler = instance.exports[`on_${handler}`];
  const fn = typeof perHandler === 'function' ? perHandler : instance.exports.on_event;
  if (typeof fn === 'function') fn(BigInt(node.id), BigInt(event), BigInt(Math.trunc(payload)));
  else log(`wasm exports no on_${handler} or on_event`);
}

// Dispatch a text event to a node's handler, passing the string as a `str` param:
// write the UTF-8 into the wasm text buffer and call on_<id>(node, event, ptr,
// len). The handler reads/validates it (text.len, ==, slice, …) and mutates the
// tree + present()s. Only the per-handler `on_<id>` shape carries a str param.
function dispatchText(node, event, str) {
  let handler = node.handlers.get(event);
  if (handler === undefined) {
    if (node.handlers.size === 1) handler = node.handlers.values().next().value;
    else return;
  }
  const fn = instance.exports[`on_${handler}`];
  if (typeof fn !== 'function') return;
  const bytes = new TextEncoder().encode(str);
  const n = Math.min(bytes.length, TEXT_CAP);
  new Uint8Array(instance.exports.memory.buffer, TEXT_BUF, TEXT_CAP).set(bytes.subarray(0, n));
  // node/event are i64 (BigInt); ptr/len are i32 address-width params (Number).
  fn(BigInt(node.id), BigInt(event), TEXT_BUF, n);
}

// Give a text field keyboard focus: position the hidden <input> over it (so iOS
// keeps it on-screen + scrolls to it), seed its value, and focus() — which must
// run inside the tap gesture to raise the soft keyboard. We draw the text/caret;
// the input only captures keystrokes.
// Start/refresh the caret blink (visible now, then toggle ~every 530ms). Called
// on focus and reset on each keystroke so the caret stays solid while typing.
function startBlink() {
  caretOn = true;
  if (blinkTimer) clearInterval(blinkTimer);
  blinkTimer = setInterval(() => { caretOn = !caretOn; if (focusedId !== null) render(); }, 530);
}
function stopBlink() { if (blinkTimer) clearInterval(blinkTimer); blinkTimer = null; caretOn = true; }

// Lift the focused field above the keyboard exactly ONCE per focus session.
// iOS fires extra visualViewport resizes (e.g. the predictive bar appears on the
// first keystroke) that would otherwise re-scroll and make the field jump again;
// the latch keeps the lift to the single keyboard-open event.
function liftFocusedOnce() {
  if (focusedId === null || kbScrolled) return;
  kbInset = viewportInset();
  if (kbInset <= 0) return;                      // keyboard not up yet — wait for the resize
  ensureFocusedVisible();
  kbScrolled = true;
}

function focusField(node) {
  focusedId = node.id;
  kbScrolled = false;
  startBlink();
  const kbd = document.getElementById('kbd');
  const cv = document.getElementById('gpu');
  const rc = layoutMap.get(node.id);
  if (kbd && cv && rc) {
    const r = cv.getBoundingClientRect();
    kbd.style.left = `${r.left + offsetX + rc.x}px`;
    kbd.style.top = `${r.top + rc.y - scrollY}px`;
    kbd.style.width = `${rc.w}px`;
    kbd.style.height = `${rc.h}px`;
    kbd.value = renderCtx.textValue(node);
    kbd.focus();
    try { kbd.setSelectionRange(kbd.value.length, kbd.value.length); } catch {}
  }
  render();
  // The keyboard animates in over a few hundred ms; the visualViewport 'resize'
  // (keyboard appearing) lifts the field and latches it. This timeout is a
  // fallback if that event doesn't fire; both go through liftFocusedOnce so the
  // field is lifted exactly once (no second jump on the first keystroke).
  setTimeout(liftFocusedOnce, 350);
}

// Drop keyboard focus and commit (a `change` event to the handler).
function blurField() {
  if (focusedId === null) return;
  const node = nodes.get(focusedId);
  focusedId = null;
  kbScrolled = false;
  stopBlink();
  kbInset = 0;                                   // keyboard is closing; reclaim the room
  const kbd = document.getElementById('kbd');
  if (kbd) kbd.blur();
  scrollY = Math.max(0, Math.min(scrollY, maxBound()));
  if (node) dispatchText(node, EVENT.change, renderCtx.textValue(node));
  render();
}

// ---- Snap: the device captures its OWN WebGPU canvas + uploads it ------------
// This is the scaling story: rendering + capture happen on the customer's device
// (their GPU), the server only stores bytes. We render a fresh frame, grab the
// canvas as a PNG blob, and POST it to the api's /api/snap with the deploy's
// snap:create token; the api stores it in R2 and returns a public URL.
let lastSnapUrl = '';
function wireSnapButton() {
  const btn = document.getElementById('snap');
  const copyBtn = document.getElementById('copy');
  if (!btn) return;
  if (!SNAP.api || !SNAP.token) { btn.disabled = true; btn.title = 'snap not configured'; if (copyBtn) copyBtn.disabled = true; return; }
  btn.addEventListener('click', async () => {
    btn.disabled = true; const label = btn.textContent; btn.textContent = '…';
    try {
      const url = await captureAndUpload();
      lastSnapUrl = url;
      // Auto-copy the URL to the clipboard so it's ready to paste immediately
      // (the click is a user gesture, so clipboard write is permitted).
      let copied = false;
      try { if (navigator.clipboard?.writeText) { await navigator.clipboard.writeText(url); copied = true; } } catch {}
      btn.textContent = '✓';
      if (copyBtn) copyBtn.disabled = false;
      const el = document.getElementById('log');
      if (el) { el.textContent = copied ? 'snap (copied): ' : 'snap: '; const a = document.createElement('a');
        a.href = url; a.textContent = url; a.target = '_blank'; a.style.color = '#5fd4ff'; el.appendChild(a); }
    } catch (e) {
      btn.textContent = '✗'; log('snap failed: ' + (e?.message || e));
    } finally {
      setTimeout(() => { btn.textContent = label; btn.disabled = false; }, 1500);
    }
  });
  // Copy: put the last snap URL on the clipboard (fast paste). Falls back to a
  // hidden textarea+execCommand if the async clipboard API is unavailable.
  if (copyBtn) copyBtn.addEventListener('click', async () => {
    if (!lastSnapUrl) return;
    const label = copyBtn.textContent;
    try {
      if (navigator.clipboard?.writeText) await navigator.clipboard.writeText(lastSnapUrl);
      else {
        const ta = document.createElement('textarea'); ta.value = lastSnapUrl;
        ta.style.position = 'fixed'; ta.style.opacity = '0'; document.body.appendChild(ta);
        ta.focus(); ta.select(); document.execCommand('copy'); ta.remove();
      }
      copyBtn.textContent = '✓';
    } catch { copyBtn.textContent = '✗'; }
    setTimeout(() => { copyBtn.textContent = label; }, 1200);
  });
}

async function captureAndUpload() {
  const canvas = document.getElementById('gpu');
  // Render a fresh frame so the WebGPU drawing buffer is populated. We must read
  // it back in the SAME turn (the buffer is cleared at the next present()).
  render();
  // Grab the canvas as a PNG blob. WebGPU canvas readback is finicky on Safari,
  // so try createImageBitmap -> 2D canvas -> blob first (forces a sync read of
  // the live buffer), then fall back to OffscreenCanvas.convertToBlob / toBlob.
  const blob = await canvasToPng(canvas);
  if (!blob) throw new Error('canvas capture returned empty (WebGPU readback failed)');
  const res = await fetch(`${SNAP.api}/api/snap`, {
    method: 'POST',
    headers: { 'authorization': `Bearer ${SNAP.token}`, 'content-type': 'image/png' },
    body: blob,
  });
  const j = await res.json().catch(() => ({}));
  if (!res.ok) throw new Error(j.error || `api ${res.status}`);
  return j.url;
}

async function canvasToPng(canvas) {
  // Path A: copy the live WebGPU buffer into a 2D canvas via an ImageBitmap.
  try {
    const bmp = await createImageBitmap(canvas);
    const off = new OffscreenCanvas(bmp.width, bmp.height);
    off.getContext('2d').drawImage(bmp, 0, 0);
    bmp.close?.();
    if (off.convertToBlob) return await off.convertToBlob({ type: 'image/png' });
  } catch {}
  // Path B: direct toBlob on the canvas (works once COPY_SRC is configured).
  return await new Promise((r) => canvas.toBlob(r, 'image/png'));
}

async function main() {
  // Stamp the build into the header title span (not the whole header — that holds
  // the Snap button too) so you can confirm you're on the latest deploy.
  const ttl = document.querySelector('header .ttl');
  if (ttl) ttl.textContent = `QView · retained · build ${BUILD}`;
  wireSnapButton();

  // Fully suppress the browser's default touch/gesture behaviour — the app owns
  // every gesture. Block iOS pinch-zoom (gesturestart), the page context menu,
  // and double-tap-zoom (a fast second tap). CSS handles scroll/callout/select.
  document.addEventListener('gesturestart', (e) => e.preventDefault());
  document.addEventListener('gesturechange', (e) => e.preventDefault());
  document.addEventListener('contextmenu', (e) => e.preventDefault());
  let lastTouchEnd = 0;
  document.addEventListener('touchend', (e) => {
    const now = Date.now();
    if (now - lastTouchEnd < 300) e.preventDefault();   // kill double-tap zoom
    lastTouchEnd = now;
  }, { passive: false });

  const canvas = document.getElementById('gpu');
  const resize = () => { canvas.width = Math.round(canvas.clientWidth * DPR); canvas.height = Math.round(canvas.clientHeight * DPR); };
  try { await initGPU(canvas); }
  catch (e) { log('WebGPU unavailable: ' + e.message + ' — open in a WebGPU-capable browser (iPad Safari 18+).'); return; }
  resize();

  const resp = await fetch('./screen.wasm');
  const bytes = await resp.arrayBuffer();
  const { instance: inst } = await WebAssembly.instantiate(bytes, ops());
  instance = inst;
  log(`retained host v${PROTOCOL_VERSION} · wasm32 (${bytes.byteLength} B) · WebGPU`);

  instance.exports._start();   // builds the retained tree + first present()

  // Pin the title bar (nodes 90/91) so it sticks at the top while content scrolls
  // beneath it. Scrollable content is CLIPPED to below the header (render() sets a
  // scissor), so scrolled text never bleeds over the sticky bar.
  for (const id of [90, 91]) { const n = nodes.get(id); if (n) n._pinned = true; }

  // A widget may expose value(node, px, py, r) -> i64 to turn a touch position
  // into a payload (e.g. a slider's value). If it does, the control is also
  // DRAGGABLE: we track the pointer and re-dispatch as it moves, so the thumb
  // follows the finger (EVENT.input during drag, EVENT.change implied on press).
  let dragNode = null, scrollDrag = null;

  const localXY = (ev) => { const r = canvas.getBoundingClientRect(); return [ev.clientX - r.left, ev.clientY - r.top]; };

  // ---- scroll momentum (inertia) ----------------------------------------------
  // On release, the scroll keeps gliding at the finger's last velocity and decays
  // exponentially (iOS-like). A drag/wheel/tap cancels any running glide.
  let momentum = 0;            // px/frame velocity
  let momentumRAF = 0;
  const FRICTION = 0.94;       // per-frame decay (higher = longer glide)
  const MIN_V = 0.4;           // stop below this speed
  const RUBBER = 0.55;         // overscroll resistance (lower = stiffer past the edge)
  const SPRING = 0.22;         // spring-back stiffness toward the edge
  // maxBound() is module-scoped (keyboard-inset aware); see above.
  // How far past an edge scrollY currently is (signed: <0 past top, >0 past bottom).
  const overshoot = () => (scrollY < 0 ? scrollY : scrollY > maxBound() ? scrollY - maxBound() : 0);
  function stopMomentum() { if (momentumRAF) { cancelAnimationFrame(momentumRAF); momentumRAF = 0; } momentum = 0; }

  // One rAF loop that does both fling momentum AND spring-back, iOS-style: while
  // in-bounds it glides with friction; once past an edge it ignores momentum and
  // springs back to the boundary; when settled, stops.
  function startMomentum(v0) {
    stopMomentum();
    momentum = v0;
    const step = () => {
      const over = overshoot();
      if (over !== 0) {
        // Past an edge: spring toward it, kill fling velocity.
        momentum = 0;
        scrollY -= over * SPRING;
        if (Math.abs(over) < 0.5) { scrollY = scrollY < 0 ? 0 : maxBound(); render(); stopMomentum(); return; }
      } else {
        momentum *= FRICTION;
        scrollY += momentum;
        if (Math.abs(momentum) < MIN_V) { stopMomentum(); return; }
      }
      render();
      momentumRAF = requestAnimationFrame(step);
    };
    momentumRAF = requestAnimationFrame(step);
  }
  // Spring back to the nearest edge if currently overscrolled (used on release
  // when there's no fling). A no-op when in-bounds.
  function settleScroll() { if (overshoot() !== 0) startMomentum(0); }

  // Long-press (touch) / right-click (mouse) -> a context menu anchored at the
  // point, for any node whose widget exposes contextMenu(node, r). Reuses the
  // shared popup primitive (so it flips/clamps near edges too).
  const LONG_PRESS_MS = 500;
  const LONG_PRESS_SLOP = 10;   // px the finger may wobble during a hold
  let longPressTimer = null, longPressFired = false, longPressXY = null;
  const cancelLongPress = () => { if (longPressTimer) { clearTimeout(longPressTimer); longPressTimer = null; } longPressXY = null; };

  // Open a context menu for the node at (px,py), anchored at the point. Returns
  // true if a menu was raised.
  function openContextMenu(px, py) {
    const hit = hitTest(px, py);
    const w = hit && widgetFor(hit.kind);
    if (!w || !w.contextMenu) return false;
    const cm = w.contextMenu(hit, renderCtx);
    if (!cm || !cm.items || cm.items.length === 0) return false;
    contextSpec = { anchor: { x: px, y: py, w: 0, h: 0 }, items: cm.items, width: cm.width ?? 200 };
    contextNode = hit;
    render();
    return true;
  }

  canvas.addEventListener('pointerdown', (ev) => {
    stopMomentum();                              // a new touch halts any scroll glide
    const [px, py] = localXY(ev);

    // If a menu is open, it captures this tap first (shared popup primitive):
    // pick an item (-> selection payload to the wasm) or dismiss on an outside tap.
    if (openDropdownId !== null || contextSpec) {
      const spec = contextSpec ? withViewport(contextSpec) : openMenuSpec();
      const target = contextSpec ? contextNode : nodes.get(openDropdownId);
      const chosen = hitMenu(spec, px, py);
      openDropdownId = null; contextSpec = null; contextNode = null;
      if (chosen !== null && chosen !== undefined && target) {
        dispatch(target, EVENT.change, chosen);     // wasm updates the field/selection
        // The platform dropdown re-themes the whole gallery live (iOS/Material/…).
        if (OPTION_PLATFORM[chosen]) setPlatform(OPTION_PLATFORM[chosen]);
      } else render();
      return;
    }

    const hit = hitTest(px, py);
    const w = hit && widgetFor(hit.kind);

    // Tapping a text field focuses it (summons the soft keyboard); tapping
    // anything else blurs the current field (dismisses it) before proceeding.
    if (hit && hit.kind === KIND.text_input) {
      ev.preventDefault();
      focusField(hit);
      return;
    }
    if (focusedId !== null) blurField();

    // No interactive target under the finger -> arm a SCROLL drag (when content
    // overflows the viewport). A vertical drag on empty space / a label scrolls.
    if (!w || (!w.hit && !w.value && !w.menuSpec && !w.contextMenu)) {
      if (contentH + 16 > viewportH) {
        scrollDrag = { startY: py, startScroll: scrollY, moved: false };
        try { canvas.setPointerCapture(ev.pointerId); } catch {}
      }
      return;
    }

    // Arm long-press if this node has a context menu (touch raises it after a hold).
    if (w && w.contextMenu) {
      longPressFired = false;
      cancelLongPress();
      longPressXY = [px, py];
      longPressTimer = setTimeout(() => { longPressTimer = null; longPressFired = openContextMenu(px, py); }, LONG_PRESS_MS);
    }
    // A widget that can raise a menu (dropdown): toggle it open.
    if (w && w.menuSpec) {
      openDropdownId = hit.id;
      render();
      return;
    }
    if (w && typeof w.value === 'function') {
      // Ranged control: set value to where you touched (down = jump-to), and arm
      // dragging so the thumb tracks the finger. preventDefault + pointer capture
      // keep the whole drag ours (no scroll-steal when it drifts vertically).
      ev.preventDefault();
      dragNode = hit;
      try { canvas.setPointerCapture(ev.pointerId); } catch {}
      dispatch(hit, EVENT.input, w.value(hit, px, py, renderCtx));
      return;
    }
    // A context-menu-only node (no press handler) waits for the long-press; don't
    // flash a press for it.
    if (w && w.contextMenu && !(hit.handlers && hit.handlers.size)) return;
    pressedId = hit.id; render();                       // immediate pressed-state flash
    dispatch(hit, EVENT.press);                         // wasm mutates + presents
    setTimeout(() => { pressedId = null; render(); }, 120);
  }, { passive: false });

  canvas.addEventListener('pointermove', (ev) => {
    // Scroll drag: translate the scene by the finger's vertical delta, tracking
    // velocity (last-frame px delta) so release can launch momentum.
    if (scrollDrag) {
      ev.preventDefault();
      const [, py] = localXY(ev);
      const dy = py - scrollDrag.startY;
      if (Math.abs(dy) > 4) scrollDrag.moved = true;
      const prev = scrollY;
      let target = scrollDrag.startScroll - dy;          // drag down -> content moves down
      // iOS rubber-band: past an edge, the content follows the finger with
      // resistance (only RUBBER of the overscroll distance) instead of 1:1.
      const max = maxBound();
      if (target < 0) target = target * RUBBER;
      else if (target > max) target = max + (target - max) * RUBBER;
      scrollY = target;
      scrollDrag.vel = scrollY - prev;                   // px since last move = velocity
      render();
      return;
    }
    // Cancel a pending long-press only if the finger moves beyond the slop radius
    // (a real hold always wobbles a few px; a true drag/scroll exceeds slop).
    if (longPressTimer && longPressXY) {
      const [sx, sy] = longPressXY;
      const [mx, my] = localXY(ev);
      if (Math.hypot(mx - sx, my - sy) > LONG_PRESS_SLOP) cancelLongPress();
    }
    if (!dragNode) return;
    ev.preventDefault();
    // Only the x drives the value; vertical drift (e.g. toward a label) is
    // ignored, so the drag holds anywhere on the canvas once captured.
    const [px, py] = localXY(ev);
    const w = widgetFor(dragNode.kind);
    dispatch(dragNode, EVENT.input, w.value(dragNode, px, py, renderCtx));
  }, { passive: false });

  const endDrag = (ev) => {
    cancelLongPress();                          // a lift before the hold elapsed = a tap, not long-press
    if (scrollDrag) {
      try { canvas.releasePointerCapture(ev.pointerId); } catch {}
      const v = scrollDrag.vel || 0;
      scrollDrag = null;
      // Flick -> glide (momentum also springs back if it hits an edge); otherwise
      // if we were left overscrolled, spring back to the boundary.
      if (Math.abs(v) > 1) startMomentum(v);
      else settleScroll();
      return;
    }
    if (!dragNode) return;
    try { canvas.releasePointerCapture(ev.pointerId); } catch {}
    dragNode = null;
  };
  canvas.addEventListener('pointerup', endDrag);
  canvas.addEventListener('pointercancel', endDrag);

  // Wheel / trackpad scroll (desktop) — clamps hard (no rubber-band for a wheel).
  canvas.addEventListener('wheel', (ev) => {
    if (maxBound() <= 0) return;
    ev.preventDefault();
    stopMomentum();
    scrollY = Math.max(0, Math.min(scrollY + ev.deltaY, maxBound()));
    render();
  }, { passive: false });

  // Right-click (desktop) -> the same context menu, anchored at the pointer.
  canvas.addEventListener('contextmenu', (ev) => {
    ev.preventDefault();                        // suppress the browser menu
    const [px, py] = localXY(ev);
    // Dismiss any open menu first; then raise the context menu (if any) here.
    openDropdownId = null; contextSpec = null; contextNode = null;
    if (!openContextMenu(px, py)) render();
  });

  // Hidden-input keystrokes drive the focused text field: the host owns the
  // value (so the field shows what's typed even if the handler ignores it), then
  // the handler gets an `input` event with the text. `blur` commits (`change`).
  const kbd = document.getElementById('kbd');
  if (kbd) {
    kbd.addEventListener('input', () => {
      if (focusedId === null) return;
      const node = nodes.get(focusedId);
      if (!node) return;
      (node._text ??= {})[TEXTKEY.value] = kbd.value;
      startBlink();                              // keep the caret solid while typing
      dispatchText(node, EVENT.input, kbd.value);
      render();
    });
    kbd.addEventListener('blur', () => { if (focusedId !== null) blurField(); });
  }
  // The soft keyboard shrinks the visual viewport; track that inset and keep the
  // focused field above it. (No-op on desktop, where visualViewport ~= layout.)
  if (window.visualViewport) {
      const onVV = () => {
      kbInset = viewportInset();
      // Lift the field only on the FIRST keyboard-open resize (latched); later
      // resizes (predictive bar, etc.) just update the inset + redraw, no jump.
      if (focusedId !== null && !kbScrolled && kbInset > 0) liftFocusedOnce();
      else render();
    };
    window.visualViewport.addEventListener('resize', onVV);
    window.visualViewport.addEventListener('scroll', onVV);
  }

  // Re-fit on a viewport change: rebuild the backing store, refresh viewportH so
  // maxBound() is computed against the NEW size (it would otherwise clamp scrollY
  // with the stale height from the last render), clamp scroll into the new range,
  // then redraw. stopMomentum so a glide in flight can't fling past the new edge.
  const refit = () => {
    resize();
    viewportH = canvas.clientHeight;
    stopMomentum();
    scrollY = Math.max(0, Math.min(scrollY, maxBound()));
    render();
  };
  // A ResizeObserver on the canvas is the RELIABLE signal: iPad Safari does not
  // dependably fire window 'resize' for Stage Manager / split-view / multitasking
  // size changes, but the observer fires whenever the element's box actually
  // changes — so the canvas, scroll bounds, and centering always track the window.
  if (typeof ResizeObserver !== 'undefined') new ResizeObserver(refit).observe(canvas);
  // Keep the window listeners too (older Safari, desktop) — refit is idempotent.
  window.addEventListener('resize', refit);
  window.addEventListener('orientationchange', () => { refit(); requestAnimationFrame(refit); });
}
main();
