// Build stamp. REGENERATED by sync.mjs on every build; the committed value is
// the fallback for a local run without a build. Shown in the gallery header.
export const BUILD = "2026-05-31 08:11Z (729dc86)";
