#!/usr/bin/env node
// gen-docs.mjs — generate the docs.q64.dev content from the compiler.
//
// Renders the `q64 doc --json` index into Starlight reference pages, mirrors
// the authoritative spec, emits an agent-ingestible `llms.txt`, and copies the
// shared brand/theme from ../web. Wired as Astro's `prebuild`/`predev` step;
// everything it writes is gitignored and never committed.
//
// It does NOT build or invoke the Zig compiler. The reference data arrives as
// `doc.json`, resolved in this order:
//   1. $DOC_JSON                          — explicit path (CI passes the artifact)
//   2. $Q64_BIN doc --json                — a local q64 binary, if present
//   3. ../q64/zig-out/bin/q64 doc --json  — the conventional local build
//   4. fixtures/doc.json                  — committed fallback so `pnpm dev` works offline
//
// The schema is versioned; we refuse a major we don't understand.

import { execFileSync } from 'node:child_process';
import {
  cpSync,
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const SCHEMA_MAJOR = 1;

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..'); // web-docs/
const repo = resolve(root, '..'); // q64 repo root
const docsDir = join(root, 'src', 'content', 'docs');
const refDir = join(docsDir, 'reference');
const specOutDir = join(docsDir, 'spec');
const specSrcDir = join(repo, 'spec');
const publicDir = join(root, 'public');

const BANNER = '<!-- AUTO-GENERATED by scripts/gen-docs.mjs — do not edit. -->';

// ---------------------------------------------------------------------------
// doc.json resolution
// ---------------------------------------------------------------------------

function loadDocJson() {
  const fromEnvFile = process.env.DOC_JSON;
  if (fromEnvFile && existsSync(fromEnvFile)) {
    return { json: readFileSync(fromEnvFile, 'utf8'), source: fromEnvFile };
  }

  const bins = [
    process.env.Q64_BIN,
    join(repo, 'q64', 'zig-out', 'bin', 'q64'),
  ].filter(Boolean);
  for (const bin of bins) {
    if (existsSync(bin)) {
      try {
        const out = execFileSync(bin, ['doc', '--json'], {
          encoding: 'utf8',
          maxBuffer: 64 * 1024 * 1024,
        });
        return { json: out, source: `${bin} doc --json` };
      } catch (err) {
        console.warn(`gen-docs: ${bin} doc --json failed (${err.message}); trying next source`);
      }
    }
  }

  const fixture = join(root, 'fixtures', 'doc.json');
  if (existsSync(fixture)) {
    return { json: readFileSync(fixture, 'utf8'), source: `${fixture} (fixture)` };
  }

  throw new Error('gen-docs: no doc.json source found (set DOC_JSON or Q64_BIN, or add fixtures/doc.json)');
}

// ---------------------------------------------------------------------------
// small helpers
// ---------------------------------------------------------------------------

function fresh(dir) {
  rmSync(dir, { recursive: true, force: true });
  mkdirSync(dir, { recursive: true });
}

function write(file, contents) {
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, contents);
}

// Escape a value for use inside a single-quoted YAML frontmatter scalar.
function yamlStr(s) {
  return `'${String(s).replace(/'/g, "''")}'`;
}

// Escape pipes/backticks-free text for a Markdown table cell.
function cell(s) {
  return String(s ?? '').replace(/\|/g, '\\|').replace(/\n/g, ' ');
}

function frontmatter(title, description) {
  const lines = ['---', `title: ${yamlStr(title)}`];
  if (description) lines.push(`description: ${yamlStr(description)}`);
  lines.push('---', '');
  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// reference pages (from doc.json.language)
// ---------------------------------------------------------------------------

function renderKeywords(lang) {
  const rows = lang.keywords
    .map((k) => `| \`${cell(k.text)}\` | \`${cell(k.kind)}\` |`)
    .join('\n');
  const body = `${frontmatter('Keywords', "q64's reserved words, generated from the lexer.")}${BANNER}

q64 reserves the following ${lang.keywords.length} keywords. This list is
generated directly from the compiler's lexer, so it never drifts from what the
parser actually recognizes.

| Keyword | Token kind |
| --- | --- |
${rows}
`;
  write(join(refDir, 'keywords.md'), body);
}

function renderTypes(lang) {
  const rows = lang.builtin_types
    .map((t) => `| \`${cell(t.name)}\` | ${cell(t.category)} | ${cell(t.doc)} |`)
    .join('\n');
  const body = `${frontmatter('Builtin types', 'Primitive and prelude types available without an import.')}${BANNER}

These types are available without an \`import\` — the numeric tower plus the
auto-prelude. See the [spec](/spec/types) for the full type system.

| Type | Category | Description |
| --- | --- | --- |
${rows}
`;
  write(join(refDir, 'types.md'), body);
}

function renderDiagnostics(lang) {
  // Index page: one table linking to each code's page.
  const rows = lang.diagnostics
    .map((d) => `| [\`${cell(d.code)}\`](/reference/diagnostics/${d.code.toLowerCase()}) | ${cell(d.subsystem)} | ${cell(d.severity)} | ${cell(d.message)} |`)
    .join('\n');
  const index = `${frontmatter('Diagnostics', 'Every diagnostic code the toolchain emits, with its meaning.')}${BANNER}

Every diagnostic the q64 toolchain emits has a stable code. The compiler points
each error at \`docs.q64.dev/diagnostics/<CODE>\`, and \`q64 explain <code>\`
prints the same information in your terminal — all from one registry.

| Code | Subsystem | Severity | Message |
| --- | --- | --- | --- |
${rows}
`;
  write(join(refDir, 'diagnostics', 'index.md'), index);

  // One page per code. These are the canonical URLs the compiler emits.
  for (const d of lang.diagnostics) {
    const page = `${frontmatter(d.code, d.message)}${BANNER}

**${d.code}** — ${d.message}

| | |
| --- | --- |
| Subsystem | ${cell(d.subsystem)} |
| Severity | ${cell(d.severity)} |

From your terminal:

\`\`\`sh
q64 explain ${d.code}
\`\`\`

:::note
Extended prose (explanation, examples, related codes) lands as the per-spec
diagnostic tables are filled in. This page is generated from the compiler's
diagnostic registry.
:::
`;
    write(join(refDir, 'diagnostics', `${d.code.toLowerCase()}.md`), page);
  }
}

// Redirect the documented host path /diagnostics/<CODE> (what the compiler
// emits) to the Starlight reference page. Emitted as static HTML redirects.
function renderDiagnosticRedirects(lang) {
  for (const d of lang.diagnostics) {
    const target = `/reference/diagnostics/${d.code.toLowerCase()}/`;
    const html = `<!doctype html><meta charset="utf-8"><title>${d.code}</title>` +
      `<meta http-equiv="refresh" content="0; url=${target}">` +
      `<link rel="canonical" href="${target}"><a href="${target}">${d.code}</a>`;
    write(join(publicDir, 'diagnostics', d.code, 'index.html'), html);
  }
}

// ---------------------------------------------------------------------------
// spec mirror (../spec/*.md -> spec/*.md with frontmatter)
// ---------------------------------------------------------------------------

function titleFromMarkdown(md, fallback) {
  const m = md.match(/^#\s+(.+)$/m);
  return m ? m[1].trim() : fallback;
}

function renderSpec() {
  if (!existsSync(specSrcDir)) {
    console.warn(`gen-docs: spec dir ${specSrcDir} not found; skipping spec mirror`);
    return;
  }
  // Top-level spec/*.md only (the conformance test corpus under spec/tests is
  // not documentation).
  const files = readdirSync(specSrcDir).filter((f) => f.endsWith('.md'));
  for (const f of files) {
    const slug = f.replace(/\.md$/, '');
    const src = readFileSync(join(specSrcDir, f), 'utf8');
    const title = slug === 'README' ? 'Spec overview' : titleFromMarkdown(src, slug);
    // Drop a leading H1 (Starlight renders the frontmatter title as the H1).
    let body = src.replace(/^#\s+.+\n+/, '');
    // Rewrite sibling links: ./foo.md and foo.md -> /spec/foo (Starlight route).
    body = body.replace(/\]\((?:\.\/)?([A-Za-z0-9_-]+)\.md(#[^)]*)?\)/g, (_m, name, hash) => {
      return `](/spec/${name === 'README' ? '' : name}${hash || ''})`;
    });
    const out = slug === 'README' ? 'index' : slug;
    write(join(specOutDir, `${out}.md`), `${frontmatter(title, `q64 spec: ${title}`)}<!-- AUTO-GENERATED from /spec/${f} — do not edit. -->\n\n${body}`);
  }
}

// ---------------------------------------------------------------------------
// llms.txt + llms-full.txt
// ---------------------------------------------------------------------------

function renderLlms(doc) {
  const lang = doc.language;
  const base = 'https://docs.q64.dev';

  const kwList = lang.keywords.map((k) => k.text).join(', ');
  const typeLines = lang.builtin_types
    .map((t) => `- \`${t.name}\` (${t.category}) — ${t.doc}`)
    .join('\n');
  const diagLines = lang.diagnostics
    .map((d) => `- ${d.code} (${d.subsystem}, ${d.severity}): ${d.message} — ${base}/diagnostics/${d.code}`)
    .join('\n');

  const llms = `# q64

> q64 is a stream-first programming language that compiles to WebAssembly.
> This file is a machine-ingestible map of the documentation for AI agents.
> Schema version ${doc.schema_version}; q64 ${doc.q64_version}.

## Documentation
- Guides: ${base}/guides/getting-started
- Reference: ${base}/reference/keywords
- Spec (authoritative): ${base}/spec
- Full reference dump: ${base}/llms-full.txt

## Keywords
${kwList}

## Builtin types
${typeLines}

## Diagnostics
Every code is documented at ${base}/diagnostics/<CODE>; \`q64 explain <CODE>\` prints the same in-terminal.
${diagLines}
`;
  write(join(publicDir, 'llms.txt'), llms);

  // Full dump also folds in the spec file list.
  let specIndex = '';
  if (existsSync(specSrcDir)) {
    specIndex = readdirSync(specSrcDir)
      .filter((f) => f.endsWith('.md'))
      .map((f) => {
        const slug = f.replace(/\.md$/, '');
        return `- ${base}/spec/${slug === 'README' ? '' : slug}`;
      })
      .join('\n');
  }
  write(join(publicDir, 'llms-full.txt'), `${llms}\n## Spec pages\n${specIndex}\n`);
}

// ---------------------------------------------------------------------------
// theme/brand copy (../web is the source of truth)
// ---------------------------------------------------------------------------

function copyTheme() {
  const css = join(repo, 'web', 'src', 'styles', 'custom.css');
  if (existsSync(css)) {
    cpSync(css, join(root, 'src', 'styles', 'custom.css'));
  } else {
    // Keep the build working if ../web is absent (e.g. partial checkout).
    write(join(root, 'src', 'styles', 'custom.css'), '/* theme placeholder — ../web/src/styles/custom.css not found */\n');
  }
  const brand = join(repo, 'web', 'public', 'brand');
  if (existsSync(brand)) {
    cpSync(brand, join(publicDir, 'brand'), { recursive: true });
  }
}

// ---------------------------------------------------------------------------
// main
// ---------------------------------------------------------------------------

function main() {
  const { json, source } = loadDocJson();
  const doc = JSON.parse(json);
  if (Math.trunc(doc.schema_version) !== SCHEMA_MAJOR) {
    throw new Error(`gen-docs: doc.json schema_version ${doc.schema_version} != supported major ${SCHEMA_MAJOR}`);
  }
  console.log(`gen-docs: doc.json from ${source} (q64 ${doc.q64_version})`);

  fresh(refDir);
  fresh(specOutDir);
  rmSync(join(publicDir, 'diagnostics'), { recursive: true, force: true });

  renderKeywords(doc.language);
  renderTypes(doc.language);
  renderDiagnostics(doc.language);
  renderDiagnosticRedirects(doc.language);
  renderSpec();
  renderLlms(doc);
  copyTheme();

  console.log(
    `gen-docs: wrote ${doc.language.keywords.length} keywords, ` +
    `${doc.language.builtin_types.length} types, ` +
    `${doc.language.diagnostics.length} diagnostics + spec mirror + llms.txt`,
  );
}

main();
