import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import sitemap from '@astrojs/sitemap';

// docs.q64.dev — the q64 language documentation.
//
// Three nav groups, two engines + one mirror (see web-docs/README.md):
//   Guides     — hand-written, committed.
//   Reference  — GENERATED from `q64 doc --json` (scripts/gen-docs.mjs).
//   Spec       — MIRRORED from ../spec/*.md at build time.
// The Reference + Spec sidebars are autogenerated from their directories so
// new generated pages appear without editing this file.
export default defineConfig({
  site: 'https://docs.q64.dev',
  trailingSlash: 'ignore',
  integrations: [
    starlight({
      title: 'q64 docs',
      description: 'Documentation for the q64 language and toolchain.',
      social: {
        github: 'https://github.com/q64-lang/q64',
      },
      sidebar: [
        { label: 'Start here', slug: 'index' },
        { label: 'Guides', autogenerate: { directory: 'guides' } },
        { label: 'Reference', autogenerate: { directory: 'reference' } },
        { label: 'Spec', autogenerate: { directory: 'spec' }, collapsed: true },
      ],
      customCss: ['./src/styles/custom.css'],
      components: {
        Footer: './src/components/Footer.astro',
      },
      head: [
        {
          tag: 'link',
          attrs: { rel: 'canonical', href: 'https://docs.q64.dev/' },
        },
      ],
    }),
    sitemap(),
  ],
});
